README.md

Add the details to the permissions section for necessary permissions to run the module.

docs: add permissions for running the module

---

examples/default/variables.tf

Issue: https://github.ibm.com/goldeneye/issues/issues/2327
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.

fix: Remove default values for security_group exampels

---

main.tf
storage.tf

This fix adds tags to resources within the VSI which are passed into the module

fix: add tags to resources

---

tests/pr_test.go

use geretain-test-resources RG

test: use geretain-test-resources RG

---

README.md
examples/default/README.md
load_balancer.tf
outputs.tf

Update Examples section of README

docs: Update Examples section of README

---

main.tf

Change the names of the VSI to prevent overlap and deletion

fix: change vsi name to prevent overlap

---

load_balancer.tf
main.tf
storage.tf
variables.tf

Fix terraform_deprecated_index tflint rule

fix: address tflint terraform_deprecated_index rule

---

.github/settings.yml

Adds the repo name and description properties and values. 
See related [PR for VPC](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/144)

ci: (settings) set name and description

---

.github/settings.yml

fix the details in settings.yml
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

docs: fix the details in settings.yml

---

.releaserc

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

ci: stop publishing to catalog

---

README.md

remove build badge
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to …

docs: remove build badge

---

.secrets.baseline
catalogValidationValues.json.template
main.tf
module-metadata.json

fixed bug which was causing kms auth policy to be created even when kms encryption was not enabled
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline …

fix: fixed bug which was causing kms auth policy to be created even when kms encryption was not enabled

---

README.md
examples/default/version.tf
examples/fscloud/version.tf
module-metadata.json
version.tf

bump the provider version to 1.54
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add …

chore(deps): update provider version

---

main.tf
module-metadata.json

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
If the CI pipeline doesn't run when you …

fix: scope the auth policy to resource group

---

main.tf
module-metadata.json

update code comment around auth policy scoping
```
/run pipeline
```

update code comment around auth policy scoping

---

.github/workflows/ci.yml
cra-config.yaml

migrate to cra config in yaml
```
/run pipeline
```

ci: migrate to cra config in yaml

---

tests/other_test.go
tests/pr_test.go

Updates test
```
/run pipeline
```

fix: update test

---

README.md

Variable doesn't exist as far as I can see.
```
/run pipeline
```

fix: variable doesn't exist

---

tests/other_test.go

Modify test setup in one of the tests.
```
/run pipeline
```

test: update other_test.go

---

outputs.tf

Issue: https://github.ibm.com/GoldenEye/issues/issues/5990
```
/run pipeline
```

fix: the fip output failing due to invalid key

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/variables.tf
examples/fscloud/variables.tf
main.tf
module-metadata.json
tests/pr_test.go

Added an example for multi-zone deployment with secondary interface configured.
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/issues/518
```
/run pipeline
```
- Merge by using "Squash …

tests: add example of secondary interface multi-zone deployment

---

examples/complete/README.md
examples/complete/main.tf

Update complete example to set `enable_floating_ip = true` so we test this functionality. 
```
/run pipeline
```

test: Update complete example to set `enable_floating_ip = true`

---

.secrets.baseline
main.tf

fix bug where floating IPs were incorrectly getting created in the default resource group
```
/run pipeline
```

fix: fix bug where floating IPs were incorrectly getting created in the default resource group

---

outputs.tf

Added the following properties to the `fip_list` output map:
* floating_ip_id
* floating_ip_crn
Fixes https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/issues/597
Added the following properties to the `fip_list` output map:
* floating_ip_id
* floating_ip_crn
```
/run pipeline
```
- Include information that users need to know about the PR in the commit …

feat: add more detail to fip_list output map

---

README.md
examples/basic/version.tf
version.tf

chore: update version constraints

---

update/schematics_update_v3.x.x_to_v4.x.x.sh
update/update-version.md

Updates to the updating instructions. Check that these make sense.
Merges into `refactor` branch.
```
/run pipeline
```

Edits to new instructions

---

main.tf

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/issues/750
Create VNI using the VSI name.
```
/run pipeline
```

fix: create VNI name based of the VSI name

---

README.md
examples/basic/version.tf
examples/complete/version.tf
examples/fscloud/version.tf
examples/snapshot/version.tf
solutions/fully-configurable/README.md
solutions/fully-configurable/version.tf
tests/pr_test.go
version.tf

IBM Cloud Virtual Network Interface (VNI) APIs have been changed to no longer allow the `auto_delete` property to be used for reserved IPs in VNIs. The IBM Cloud Terraform Provider was still including this property, with no way to remove it, in all VNI API calls which would cause the following error:
> CreateVirtualNetworkInterfaceWithContext failed unevaluatedProperty 'auto_delete' not allowed on 'VirtualNetworkInterfacePrimaryIPPrototype'
The latest version `v1.78.4` has fixed this issue, bringing the property format of VNIs in-line with current API payloads.
This PR will set a minimum version of v1.78.4 to avoid this issue going forward.
Sets minimum required IBM Cloud provider version to v1.78.4 to avoid "auto_delete not allowed on VirtualNetworkInterfacePrimaryIPPrototype" bug
If the …

fix: ibmcloud provider fix for reserved_ip vni

---

.catalog-onboard-pipeline.yaml

Disable DA auto publish

---

ibm_catalog.json
tests/go.mod
tests/go.sum
tests/pr_test.go

Update DA dependencies version and use existing secrets manager in addon test.
```
/run pipeline
```

fix(deps): update DA dependencies + tests cleanup
